version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.4
    - image: circleci/postgres:11.4
    working_directory: ~/django_project
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          sudo pip install pipenv
          pipenv install
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
workflows:
  version: 2
  workflow:
    jobs:
    - build